# Generated by Django 3.2.9 on 2021-11-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=150)),
                ('customer_name', models.CharField(max_length=100)),
                ('cosutmer_phone', models.IntegerField(max_length=10)),
                ('product_name', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('date', models.DateField(null=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
